FROM python:3.12
WORKDIR /app

# 配置pip使用清华源
#RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
#RUN pip config set global.trusted-host pypi.tuna.tsinghua.edu.cn
# 安装Poetry
RUN pip install poetry

# 复制项目文件
COPY pyproject.toml poetry.lock* ./

# RUN poetry config repositories.tsinghua https://pypi.tuna.tsinghua.edu.cn/simple/ && \
#    poetry config virtualenvs.create false
# 安装项目依赖（包括所有groups）
RUN poetry install --no-root --all-extras -v

# 复制应用代码
COPY . .
RUN rm -f config.yaml
# 安装项目本身
# RUN poetry install --no-dev

# 确保脚本可访问
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONPATH=/app
ENV api_key=""

EXPOSE 8080
CMD bash -c 'python3 main.py ./mcp/mcp_server.py'