site_name: i18n-agent-action
theme: material

docs_dir: ./docs

plugins:
  - i18n:
      docs_structure: suffix
      default_language: en  # 添加默认语言设置
      languages:  # 改为字典格式
        en:
          name: English
          build: true
        zh:
          name: Chinese
          build: true