site_name: i18n-agent-action
theme: material

docs_dir: ./docs

plugins:
  - i18n:
      docs_structure: suffix
      languages:  # 改为字典格式
        - locale: en
          name: English
          default: true
        - locale: zh
          name: Chinese
          build: true
        - locale: es  # Español (西班牙语)
          name: Español
          build: true
        - locale: fr  # Français (法语)
          name: Français
          build: true
        - locale: ja  # 日本語 (日语)
          name: 日本語
          build: true
        - locale: ar  # العربية (阿拉伯语)
          name: العربية
          build: true