site_name: i18n-agent-action
theme: material

docs_dir: ./docs

plugins:
  - i18n:
      docs_structure: suffix
      default_language: en
      languages:  # 改回列表格式
        - locale: en
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true