import logging

import flet as ft
from chatmessage import ChatMessage, Message
from fileMgr import FileManager
from soundmgr import SoundManager
from translationbridge import translate_text


class ChatApp:
    def __init__(self, page: ft.Page):
        self.page = page
        # 1st class area
        ## Text input
        self.chat = ft.ListView(
            expand=True,
            spacing=10,
            auto_scroll=True,
        )
        ## STT
        self.sound_manager = SoundManager(self.page, self.chat)
        ## file mgr
        self.file_manager = FileManager(self.page, self.chat)
        # todo/workaround
        self.setup_ui()

    def get_content(self):
        """返回翻译应用的内容"""
        return self.main_content

    def setup_ui(self):
        # 创建消息输入框
        self.new_message = ft.TextField(
            hint_text="请输入要翻译的文本...",
            multiline=True,
            min_lines=1,
            max_lines=5,
            shift_enter=True,
            filled=True,
            expand=True,
            on_submit=self.send_message_click,
        )

        # 创建发送按钮
        self.send_button = ft.IconButton(
            icon=ft.Icons.SEND_ROUNDED,
            tooltip="发送翻译",
            on_click=self.send_message_click,
        )

        # 创建上传文件按钮
        self.upload_button = self.file_manager.upload_button

        # 创建录音按钮
        self.record_buttons = self.sound_manager.create_record_button()

        # 创建主内容区域
        self.main_content = ft.Column(
            [
                ft.Row(
                    [
                        ft.Text(
                            "i18n agent",
                            theme_style=ft.TextThemeStyle.HEADLINE_LARGE,
                        ),
                        ft.Text(
                            "Icons made by Good Ware from www.flaticon.com \nTranslation Content Generated by LLM",
                            theme_style=ft.TextThemeStyle.LABEL_SMALL,
                        ),
                    ],
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                ),
                ft.Container(
                    content=self.chat,
                    border=ft.Border.all(),
                    border_radius=5,
                    padding=10,
                    expand=True,
                ),
                ft.Row(
                    [
                        self.new_message,
                        self.send_button,
                        self.upload_button,
                    ]
                ),
                self.record_buttons,  # 添加录音按钮
                ft.Container(height=10),
            ],
            alignment=ft.MainAxisAlignment.START,
            expand=True,
        )

        # 设置页面布局 - 直接添加主内容区域，不再包含左侧边栏
        # 注意：这里移除了 self.page.add(self.main_content)，因为现在通过导航栏切换

    async def send_message_click(self, e):
        if self.new_message.value != "":
            text = self.new_message.value
            await self.Add_newMsg(text)
            self.new_message.value = ""
            await self.new_message.focus()
            self.page.update()

    def add_message(self, message: Message):
        if message.message_type == "chat_message":
            m = ChatMessage(message, self.sound_manager.engine, self.page, None)
            self.chat.controls.append(m)
        self.page.update()

    async def Add_newMsg(self, text):
        self.add_message(
            Message(
                user_name="User",
                text=text,
                message_type="chat_message",
            )
        )
        logging.info("send content to translation_bridge")
        result = translate_text(self.new_message.value)
        logging.info(result)
        self.add_message(
            Message(
                user_name="Agent",
                text=result,
                message_type="chat_message",
            )
        )
