import logging
import os
import sys
from typing import Dict

import flet as ft

# import flet_audio_recorder as ftar
import pyttsx3
from chatmessage import ChatMessage, Message
from leftsidebar import LeftSidebar
from rightsidebar import RightSidebar

# 添加项目根目录到Python路径
root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(root_dir)

from AgentUtils.ExpiringDictStorage import ExpiringDictStorage  # noqa: E402
from AgentUtils.span import Span_Mgr  # noqa: E402
from Business.translate import translateAgent  # noqa: E402


class TranslationApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "i18n agent"
        self.page.theme_mode = ft.ThemeMode.LIGHT
        self.log_contents = []
        self.recording_path = ""
        self.prog_bars: Dict[str, ft.ProgressRing] = {}
        # self.audio_rec = ftar.AudioRecorder(
        #     audio_encoder=ftar.AudioEncoder.WAV,
        #     on_state_changed=self.handle_state_change,
        # )
        self.setup_ui()

    def handle_state_change(self, e):
        print(f"State Changed: {e.data}")

    def handle_start_recording(self, e):
        self.recording_path = os.path.join(self.app_data_path, "test-audio-file.wav")
        logging.info(f"StartRecording: {self.recording_path}")
        # .start_recording(self.recording_path)

    def handle_stop_recording(self, e):
        logging.info("tbd")
        # try:
        #     output_path = self.audio_rec.stop_recording(wait_timeout=30)
        #     logging.info(f"StopRecording: {output_path}")
        # except Exception as ex:
        #     logging.info(f"Error stopping recording: {ex}")

    def setup_ui(self):
        # 创建聊天消息区域
        self.chat = ft.ListView(
            expand=True,
            spacing=10,
            auto_scroll=True,
        )
        self.engine = pyttsx3.init()

        # 创建消息输入框
        self.new_message = ft.TextField(
            hint_text="请输入要翻译的文本...",
            multiline=True,
            min_lines=1,
            max_lines=5,
            shift_enter=True,
            filled=True,
            expand=True,
            on_submit=self.send_message_click,
        )

        # 创建发送按钮
        self.send_button = ft.IconButton(
            icon=ft.Icons.SEND_ROUNDED,
            tooltip="发送翻译",
            on_click=self.send_message_click,
        )

        # 创建文件选择器
        self.file_picker = ft.FilePicker(
            on_result=self.file_picker_result, on_upload=self.on_upload_progress
        )
        self.page.overlay.append(self.file_picker)

        # 创建上传文件按钮
        self.upload_button = ft.IconButton(
            icon=ft.Icons.UPLOAD_FILE,
            tooltip="上传文件",
            on_click=lambda _: self.file_picker.pick_files(allow_multiple=True),
        )

        # 创建文件列表容器
        self.files_container = ft.Column()

        # 创建录音按钮（注释掉并隐藏）
        self.record_btn = ft.ElevatedButton(
            "Start Audio Recorder",
            on_click=self.handle_start_recording,
            visible=False,  # 隐藏录音按钮
        )
        self.stp_record_btn = ft.ElevatedButton(
            "Stop Audio Recorder",
            on_click=self.handle_stop_recording,
            visible=False,  # 隐藏停止录音按钮
        )

        # 创建左侧边栏切换按钮
        self.left_sidebar_toggle = ft.IconButton(
            icon=ft.Icons.MENU,
            tooltip="显示/隐藏设置",
            on_click=self.toggle_left_sidebar,
        )

        # 创建右侧边栏切换按钮
        self.right_sidebar_toggle = ft.IconButton(
            icon=ft.Icons.BAR_CHART,
            tooltip="显示/隐藏统计",
            on_click=self.toggle_right_sidebar,
        )

        # 创建日志查看按钮
        self.log_view_toggle = ft.IconButton(
            icon=ft.Icons.LIST_ALT, tooltip="查看日志", on_click=self.show_logs
        )

        # 创建左侧边栏
        self.app_data_path = os.getenv("FLET_APP_STORAGE_DATA")
        self.storage_file_path = os.path.join(self.app_data_path, "data_store.json")
        self.storage = ExpiringDictStorage(
            filename=self.storage_file_path, expiry_days=7
        )
        self.left_sidebar = LeftSidebar(self, self.storage)

        # 创建右侧边栏
        self.right_sidebar = RightSidebar(self)

        # 创建主内容区域
        self.main_content = ft.Column(
            [
                ft.Row(
                    [
                        ft.Text(
                            "i18n agent", theme_style=ft.TextThemeStyle.HEADLINE_LARGE
                        ),
                        ft.Text(
                            "Icons made by Good Ware from www.flaticon.com \nTranslation Content Generated by LLM",
                            theme_style=ft.TextThemeStyle.LABEL_SMALL,
                        ),
                        ft.Row(
                            [
                                self.left_sidebar_toggle,
                                self.right_sidebar_toggle,
                                self.log_view_toggle,
                            ],
                            spacing=5,
                        ),
                    ],
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                ),
                ft.Container(
                    content=self.chat,
                    border=ft.border.all(1, ft.Colors.OUTLINE),
                    border_radius=5,
                    padding=10,
                    expand=True,
                ),
                ft.Row(
                    [
                        self.new_message,
                        self.upload_button,  # 添加上传按钮
                        self.send_button,
                    ]
                ),
                self.files_container,  # 显示文件上传进度
                ft.Container(height=10),
                self.record_btn,
                self.stp_record_btn,
            ],
            alignment=ft.MainAxisAlignment.START,
            expand=True,
        )

        # 创建日志弹窗
        self.log_dialog = ft.AlertDialog(
            title=ft.Text("查看日志"),
            content=ft.Text(""),
            alignment=ft.alignment.center,
            on_dismiss=lambda e: logging.info("Dialog dismissed!"),
            title_padding=ft.padding.all(25),
        )

        self.page.overlay.append(self.log_dialog)
        # self.page.overlay.append(self.audio_rec)

        # 设置页面布局
        self.page.add(
            ft.Row(
                [
                    self.left_sidebar,
                    ft.VerticalDivider(width=1, visible=False),
                    self.main_content,
                    ft.VerticalDivider(width=1, visible=False),
                    self.right_sidebar,
                ],
                expand=True,
            )
        )

    def file_picker_result(self, e: ft.FilePickerResultEvent):
        self.upload_button.disabled = True if e.files is None else False
        self.prog_bars.clear()
        self.files_container.controls.clear()

        if e.files is not None:
            for f in e.files:
                prog = ft.ProgressRing(value=0, bgcolor="#eeeeee", width=20, height=20)
                self.prog_bars[f.name] = prog
                self.files_container.controls.append(ft.Row([prog, ft.Text(f.name)]))

        self.page.update()

        # 自动开始上传
        if e.files:
            self.upload_files()

    def on_upload_progress(self, e: ft.FilePickerUploadEvent):
        if e.file_name in self.prog_bars:
            self.prog_bars[e.file_name].value = e.progress
            self.prog_bars[e.file_name].update()

            # 当上传完成时记录日志
            if e.progress >= 1.0:
                self.log_file_upload(e.file_name)

    def upload_files(self):
        if (
            self.file_picker.result is not None
            and self.file_picker.result.files is not None
        ):
            uf = []
            for f in self.file_picker.result.files:
                # 获取上传URL，文件将保存在FLET_APP_STORAGE_TEMP目录中
                upload_url = self.page.get_upload_url(f.name, 600)
                uf.append(
                    ft.FilePickerUploadFile(
                        f.name,
                        upload_url=upload_url,
                    )
                )
            self.file_picker.upload(uf)

    def log_file_upload(self, filename):
        """记录文件上传日志"""
        temp_path = os.getenv("FLET_APP_STORAGE_DATA")
        filepath = os.path.join(temp_path, filename) if temp_path else filename

        log_message = f"文件上传成功: {filename} -> {filepath}"
        logging.info(log_message)

        # 这里可以添加后续功能扩展的调用
        # 例如: self.process_uploaded_file(filepath)

    def send_message_click(self, e):
        if self.new_message.value != "":
            # 添加用户消息到聊天
            self.add_message(
                Message(
                    user_name="User",
                    text=self.new_message.value,
                    message_type="chat_message",
                )
            )

            # 调用翻译功能
            self.translate_text(e)

            self.new_message.value = ""
            self.new_message.focus()
            self.page.update()

    def add_message(self, message: Message):
        if message.message_type == "chat_message":
            m = ChatMessage(message, self.engine)
        self.chat.controls.append(m)
        self.page.update()

    def toggle_left_sidebar(self, e=None):
        self.left_sidebar.visible = not self.left_sidebar.visible
        # 更新分割线的可见性
        self.page.controls[0].controls[1].visible = self.left_sidebar.visible
        # 更新按钮图标
        self.left_sidebar_toggle.icon = (
            ft.Icons.MENU if not self.left_sidebar.visible else ft.Icons.ARROW_BACK
        )
        self.page.update()

    def toggle_right_sidebar(self, e=None):
        self.right_sidebar.visible = not self.right_sidebar.visible
        # 更新分割线的可见性
        self.page.controls[0].controls[3].visible = self.right_sidebar.visible
        # 更新按钮图标
        self.right_sidebar_toggle.icon = (
            ft.Icons.BAR_CHART
            if not self.right_sidebar.visible
            else ft.Icons.ARROW_FORWARD
        )
        self.page.update()

    def show_logs(self, e):
        # 读取日志文件并显示最近30条
        app_data_path = os.getenv("FLET_APP_STORAGE_DATA")
        log_file_path = (
            os.path.join(app_data_path, "app.log") if app_data_path else "app.log"
        )

        self.log_contents = []
        if os.path.exists(log_file_path):
            try:
                with open(log_file_path, "r", encoding="utf-8") as f:
                    lines = f.readlines()
                # 获取最后30行
                recent_lines = lines[-10:] if len(lines) > 10 else lines
                self.log_contents = [
                    ft.Text(line.strip(), size=5) for line in recent_lines
                ]
            except Exception as e:
                self.log_contents = [
                    ft.Text(f"读取日志文件出错: {str(e)}", size=5, color=ft.Colors.RED)
                ]
        else:
            self.log_contents = [
                ft.Text("日志文件不存在", size=12, color=ft.Colors.RED)
            ]

        self.log_dialog.content.value = str(self.log_contents)
        self.log_dialog.update()
        self.page.open(self.log_dialog)

    def translate_text(self, e):
        # 获取最后一条用户消息
        user_message = None
        for msg in reversed(self.chat.controls):
            if isinstance(msg, ChatMessage) and msg.user_name == "User":
                user_message = msg.text
                break

        if not user_message:
            return

        # 模拟翻译功能
        LLM_client = self.left_sidebar.GenClient()
        storage = self.left_sidebar.get_storage()
        context = self.left_sidebar.getTranslationContext()
        span_mgr = Span_Mgr(storage)
        root_span = span_mgr.create_span("Root operation")
        TsAgent = translateAgent(LLM_client, span_mgr)

        if user_message:
            # 尝试找到匹配的模拟翻译
            result = TsAgent.translate(
                context, context.target_language, user_message, root_span
            )
            logging.info(result)

            # 添加翻译结果到聊天
            self.add_message(
                Message(
                    user_name="Agent",
                    text=result,
                    message_type="chat_message",
                )
            )

            self.left_sidebar.AppendHistory(user_message, result)
