import logging
import os

import flet as ft
from chatmessage import ChatMessage, Message
from FileDownloader import FileDownloader
from fileMgr import FileManager
from leftsidebar import LeftSidebar
from logViewer import LogViewer
from share_manager import ShareManager  # 导入新的ShareManager类
from soundmgr import SoundManager
from translationbridge import TranslationBridge

class TranslationApp:
    def __init__(self, page: ft.Page):
        self.page = page
        self.page.title = "i18n agent"
        self.page.theme_mode = ft.ThemeMode.LIGHT
        self.app_data_path = os.getenv("FLET_APP_STORAGE_DATA")
        # 1st class area
        ## LLM config
        self.left_sidebar = LeftSidebar(self)
        ## Text input
        self.chat = ft.ListView(
            expand=True,
            spacing=10,
            auto_scroll=True,
        )
        ## STT
        self.sound_manager = SoundManager(page)
        self.file_downloader = FileDownloader(page)
        ## social media
        self.share_manager = ShareManager(page)
        ## Debug
        self.log_viewer = LogViewer(page)
        # 2nd class area
        ## agent
        self.translation_bridge = TranslationBridge(self.left_sidebar)
        ## file mgr
        self.file_manager = FileManager(page, self.chat, self.translation_bridge)
        # todo/workaround
        self.setup_ui()

    async def handle_stop_recording(self, e):
        """处理停止录音"""
        await self.sound_manager.stop_recording()
        ## stream.result.text is STT result
        text = await self.sound_manager.sound_to_text()
        logging.info(text)
        self.add_message(
            Message(
                user_name="User",
                text=text,
                message_type="chat_message",
            )
        )
        result = self.translation_bridge.translate_text(text)
        logging.info(result)
        # 添加翻译结果到聊天
        self.add_message(
            Message(
                user_name="Agent",
                text=result,
                message_type="chat_message",
            )
        )

    def setup_ui(self):
        self.file_downloader.visible()
        # 创建消息输入框
        self.new_message = ft.TextField(
            hint_text="请输入要翻译的文本...",
            multiline=True,
            min_lines=1,
            max_lines=5,
            shift_enter=True,
            filled=True,
            expand=True,
            on_submit=self.send_message_click,
        )

        # 创建发送按钮
        self.send_button = ft.IconButton(
            icon=ft.Icons.SEND_ROUNDED,
            tooltip="发送翻译",
            on_click=self.send_message_click,
        )

        # 创建上传文件按钮
        self.upload_button = self.file_manager.upload_button

        # 创建录音按钮
        self.record_buttons = self.sound_manager.create_record_button(
            self.handle_stop_recording,
            visible=True,  # 可以根据需要设置为False来隐藏录音按钮
        )

        # 创建左侧边栏切换按钮
        self.left_sidebar_toggle = ft.IconButton(
            icon=ft.Icons.MENU,
            tooltip="显示/隐藏设置",
            on_click=self.toggle_left_sidebar,
        )
        self.log_view_toggle = self.log_viewer.create_ui()
        self.share_button = self.share_manager.create_ui()

        # 创建主内容区域
        self.main_content = ft.Column(
            [
                ft.Row(
                    [
                        ft.Text(
                            "i18n agent",
                            theme_style=ft.TextThemeStyle.HEADLINE_LARGE,
                        ),
                        ft.Text(
                            "Icons made by Good Ware from www.flaticon.com \nTranslation Content Generated by LLM",
                            theme_style=ft.TextThemeStyle.LABEL_SMALL,
                        ),
                        ft.Row(
                            [
                                self.left_sidebar_toggle,
                                self.log_view_toggle,
                                self.share_button,  # 添加分享按钮
                            ],
                            spacing=5,
                        ),
                    ],
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                ),
                # 下载区域
                ft.Card(
                    content=ft.Container(
                        content=ft.Column(
                            [
                                ft.Text(
                                    "模型文件下载",
                                    style=ft.TextThemeStyle.TITLE_MEDIUM,
                                ),
                                self.file_downloader.download_status_text,
                                ft.Row(
                                    [
                                        self.file_downloader.download_progress_bar,
                                        self.file_downloader.download_progress_text,
                                    ],
                                    alignment=ft.MainAxisAlignment.CENTER,
                                ),
                                ft.Row(
                                    [
                                        self.file_downloader.download_btn,
                                        self.file_downloader.cancel_download_btn,
                                    ],
                                    alignment=ft.MainAxisAlignment.CENTER,
                                ),
                            ],
                            spacing=10,
                        ),
                        padding=15,
                    )
                ),
                ft.Container(
                    content=self.chat,
                    border=ft.Border.all(),
                    border_radius=5,
                    padding=10,
                    expand=True,
                ),
                ft.Row(
                    [
                        self.new_message,
                        self.upload_button,
                        self.send_button,
                    ]
                ),
                self.record_buttons,  # 添加录音按钮
                ft.Container(height=10),
            ],
            alignment=ft.MainAxisAlignment.START,
            expand=True,
        )

        # 设置页面布局
        self.page.add(
            ft.Row(
                [
                    self.left_sidebar,
                    ft.VerticalDivider(width=1, visible=False),
                    self.main_content,
                ],
                expand=True,
            )
        )

    def send_message_click(self, e):
        if self.new_message.value != "":
            # 添加用户消息到聊天
            self.add_message(
                Message(
                    user_name="User",
                    text=self.new_message.value,
                    message_type="chat_message",
                )
            )
            try:
                logging.info("send content to translation_bridge")
                result = self.translation_bridge.translate_text(self.new_message.value)
                logging.info(result)
                # 添加翻译结果到聊天
                self.add_message(
                    Message(
                        user_name="Agent",
                        text=result,
                        message_type="chat_message",
                    )
                )
            except Exception as e:
                error_msg = f"翻译失败: {str(e)}"
                logging.error(error_msg)
            self.new_message.value = ""
            self.new_message.focus()
            self.page.update()

    def add_message(self, message: Message):
        if message.message_type == "chat_message":
            m = ChatMessage(message, self.sound_manager.engine, self.page, None)
        self.chat.controls.append(m)
        self.page.update()

    def toggle_left_sidebar(self, e=None):
        self.left_sidebar.visible = not self.left_sidebar.visible
        # 更新分割线的可见性
        self.page.controls[0].controls[1].visible = self.left_sidebar.visible
        # 更新按钮图标
        self.left_sidebar_toggle.icon = (
            ft.Icons.MENU if not self.left_sidebar.visible else ft.Icons.ARROW_BACK
        )
        self.page.update()

    # def save_html_page(url, filename="saved_page.html"):
    # """


# 保存HTML页面到本地文件

# Args:
#     url (str): 要下载的网页URL
#     filename (str): 保存的文件名，默认为"saved_page.html"

# Returns:
#     str: 保存的文件路径
# """
# # 设置SSL上下文
# ssl_context = ssl.create_default_context()
# ssl_context.check_hostname = False
# ssl_context.verify_mode = ssl.CERT_NONE

# 设置请求头
# headers = {
#     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
# }

# logging.info(f"正在下载: {url}")

# try:
# 下载HTML内容
#   req = urllib.request.Request(url, headers=headers)
#   with urllib.request.urlopen(req, context=ssl_context) as response:
#       html_content = response.read().decode('utf-8', errors='replace')

# 确保文件名以.html结尾
#  if not filename.endswith('.html'):
#      filename += '.html'

# 保存HTML文件
#  with open(filename, 'w', encoding='utf-8') as f:
#      f.write(html_content)

#  logging.info(f"页面已保存到: {os.path.abspath(filename)}")
#  return os.path.abspath(filename)

# except Exception as e:
# raise Exception(f"下载失败: {str(e)}")
