name: Process Changed Markdown Files

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'

jobs:
  process-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed markdown files (excluding all i18n variants)
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          since_last_remote_commit: true
          separator: ","
          files: |
            docs/**/*.md
          files_ignore: |
            docs/**/*.*.md  # 匹配所有语言变体

      - name: Add prefix to each file
        if: steps.changed-files.outputs.all_changed_files != ''
        id: addprefix
        run: |
            PREFIX="/workspace/"
            PREPENDED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | sed "s|^|$PREFIX|g" | sed "s|,|,$PREFIX|g")
            echo "PREPENDED_FILES=${PREPENDED_FILES}" >> $GITHUB_OUTPUT

      - name: Print and use changed files
        if: steps.addprefix.outputs.PREPENDED_FILES != ''
        run: |
          echo "Changed markdown files (excluding all i18n variants):"
          echo "${{ steps.addprefix.outputs.PREPENDED_FILES }}"

      - name: Use this Action
        id: use-action
        uses: SamYuan1990/i18n-agent-action@main
        with:
          apikey: ${{ secrets.API_KEY }}
          RESERVED_WORD: i18n-agent-action
          DOCS_FOLDER: /workspace/docs
          CONFIG_FILE: /workspace/mkdocs.yml
          workspace: /home/runner/work/i18n-agent-action/i18n-agent-action
          FILE_LIST: ${{ steps.addprefix.outputs.PREPENDED_FILES }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "auto i18n with GHA"
          body: "This PR do i18n for you"
          branch: feature/i18n-${{ github.run_id }}
          base: main  # 目标分支
          draft: false